server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: userdetails
          uri: lb://userdetails
          predicates:
            - Path=/v1/**

        - id: postdetails
          uri: lb://postdetails
          predicates:
            - Path=/v1/**

#        - id: AdminApp
#          uri: lb://AdminApp
#          predicates:
#            - Path=/admin/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/